const icons: { [key: string]: string } = {
  user_left: "./icons/users/user_left.svg",
  user_right: "./icons/users/user_right.svg",
  kick: "./icons/drums/kick.svg",
  tom: "./icons/drums/tom.svg",
  snare: "./icons/drums/snare.svg",
  hi_hat: "./icons/drums/hi_hat.svg",
  closed_hat: "./icons/drums/closed_hat.svg",
  drums: "./icons/drums.svg",
  keyboard: "./icons/keyboard.svg",
  octave_up: "./icons/octave_up.svg",
  octave_down: "./icons/octave_down.svg",
  soundclips: "./icons/music_note.svg",
  back: "./icons/previous_arrow.svg",
  cog_inner: "./icons/cog/cog_inner.svg",
  cog_outer: "./icons/cog/cog_outer.svg",
  play: "./icons/play.svg",
  stop: "./icons/stop.svg",
  mold_castIn: "./icons/neumorphic_mold_cast_in.svg",
  mold_bumpedUp: "./icons/neumorphic_mold_bumped_up.svg",
};
export default icons;
