export type Icon =
  | "plus"
  | "close"
  | "confirm"
  | "volume#full"
  | "volume#partial"
  | "volume#mute"
  | "config"
  | "leave"
  | "enter"
  | "enter#bordered"
  | "keyboard"
  | "keyboard#thin"
  | "drumkit"
  | "jammers"
  | "menu"
  | "tutorial";
