export type Sample =
  | "Closed Hat - 808"
  | "Closed Hat - Acoustic"
  | "Closed Hat - Dist"
  | "Closed Hat - Massamolla"
  | "Closed Hat - Metal"
  | "Closed Hat - Micro"
  | "Closed Hat - Pedal"
  | "Closed Hat - Reso"
  | "Closed Hat - Ring"
  | "Closed Hat - Salty"
  | "Closed Hat - Springwater"
  | "Closed Hat - Stutter"
  | "Closed Hat - Sweet"
  | "Closed Hat - Wonky"
  | "Closed Hat - Zippo"
  | "Hat - 808"
  | "Hat - Accoustic"
  | "Hat - Analog"
  | "Hat - Cymbal"
  | "Hat - House 2"
  | "Hat - House"
  | "Hat - Noise"
  | "Hat - Slick"
  | "Hat - Tape"
  | "Hat - Tight"
  | "Kick - 808"
  | "Kick - Boiler"
  | "Kick - Coffee Shop"
  | "Kick - Devastate"
  | "Kick - Duster"
  | "Kick - Fistpump"
  | "Kick - Hard"
  | "Kick - Juicy"
  | "Kick - Nailgun"
  | "Kick - Quake"
  | "Kick - Shower"
  | "Kick - Sonya"
  | "Kick - Swooshy"
  | "Kick - Thumpster"
  | "Kick - Zapper"
  | "Snare - 1982 Drive"
  | "Snare - Analog"
  | "Snare - Breathe"
  | "Snare - Cassette"
  | "Snare - Clappers Delight"
  | "Snare - Frogger"
  | "Snare - Hype Machine"
  | "Snare - LoFi"
  | "Snare - Nu Disco"
  | "Snare - OG"
  | "Snare - Papercut"
  | "Snare - Piccolo"
  | "Snare - Slammer"
  | "Snare - Snapper"
  | "Snare - Suction"
  | "Tom - 808"
  | "Tom - Accoustic 1"
  | "Tom - Accoustic 2"
  | "Tom - Accoustic 3"
  | "Tom - Analog"
  | "Tom - Chirptune"
  | "Tom - FM"
  | "Tom - Lofi"
  | "Tom - Rototom"
  | "Tom - Short"
  | "A1"
  | "A2"
  | "A3"
  | "A4"
  | "A5"
  | "A6"
  | "A7"
  | "As1"
  | "As2"
  | "As3"
  | "As4"
  | "As5"
  | "As6"
  | "As7"
  | "B1"
  | "B2"
  | "B3"
  | "B4"
  | "B5"
  | "B6"
  | "B7"
  | "C1"
  | "C2"
  | "C3"
  | "C4"
  | "C5"
  | "C6"
  | "C7"
  | "C8"
  | "Cs1"
  | "Cs2"
  | "Cs3"
  | "Cs4"
  | "Cs5"
  | "Cs6"
  | "Cs7"
  | "D1"
  | "D2"
  | "D3"
  | "D4"
  | "D5"
  | "D6"
  | "D7"
  | "Ds1"
  | "Ds2"
  | "Ds3"
  | "Ds4"
  | "Ds5"
  | "Ds6"
  | "Ds7"
  | "E1"
  | "E2"
  | "E3"
  | "E4"
  | "E5"
  | "E6"
  | "E7"
  | "F1"
  | "F2"
  | "F3"
  | "F4"
  | "F5"
  | "F6"
  | "F7"
  | "Fs1"
  | "Fs2"
  | "Fs3"
  | "Fs4"
  | "Fs5"
  | "Fs6"
  | "Fs7"
  | "G1"
  | "G2"
  | "G3"
  | "G4"
  | "G5"
  | "G6"
  | "G7"
  | "Gs1"
  | "Gs2"
  | "Gs3"
  | "Gs4"
  | "Gs5"
  | "Gs6"
  | "Gs7";
